- hosts: tvm-dev

  environment:
    # Set PATH so ansible.builtin.shell module can find 'west' command
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

  tasks:
  - name: Install necessary packages for Zephyr
    apt:
      pkg:
        - git
        - cmake
        - ninja-build
        - gperf
        - ccache
        - dfu-util
        - device-tree-compiler
        - wget
        - python3-dev
        - python3-pip
        - python3-setuptools
        - python3-tk
        - python3-wheel
        - xz-utils
        - file
        - make
        - gcc
        - gcc-multilib
        - g++-multilib
        - libsdl2-dev
        - minicom
    become: yes

  - name: Install west cli
    pip:
      name: west
      extra_args: "--user -U"

  - name: Add west cli to PATH
    blockinfile:
      dest: "{{ ansible_env.HOME }}/.bashrc"
      block: |
        export PATH=~/.local/bin:"$PATH"
      marker: '# {mark} ANSIBLE MANAGED BLOCK - west'
      insertafter: EOF

  - name: Get Zephyr v2.5-branch src and initialize its repo
    # Run task only once per playbook run
    run_once: true
    ansible.builtin.shell: |
      west init --mr v2.5-branch {{ ansible_env.HOME }}/zephyrproject
      cd {{ ansible_env.HOME }}/zephyrproject
      west update
      west zephyr-export
    args:
      executable: /bin/bash
      # $HOME/zephyrproject exists, skip task
      creates: "{{ ansible_env.HOME }}/zephyrproject"
    notify: Install Zephyr Python dependencies

  - name: Clone TVM github repository
    ansible.builtin.git:
      repo: https://github.com/apache/tvm.git
      dest: "{{ lookup('env', 'HOME') }}/git/tvm"
      recursive: yes

  handlers:
  - name: Install Zephyr Python dependencies
    pip:
      requirements: "{{ ansible_env.HOME }}/zephyrproject/zephyr/scripts/requirements.txt"
      extra_args: "--user"
