- hosts: tvm-dev

  tasks:
  - name: Clone TVM github repository
    ansible.builtin.git:
      repo: https://github.com/apache/tvm.git
      dest: "{{ lookup('env', 'HOME') }}/git/tvm"
      recursive: yes
